services:
  - name: n8n
    type: web
    runtime: docker
    plan: free
    region: ohio
    repo: https://github.com/naw334/n8n-docker-render
    branch: main
    dockerfilePath: ./Dockerfile
    envVars:
      - key: N8N_BASIC_AUTH_ACTIVE
        value: "true"
      - key: N8N_BASIC_AUTH_USER
        sync: false
      - key: N8N_BASIC_AUTH_PASSWORD
        sync: false
      - key: WEBHOOK_TUNNEL_URL
        value: https://n8n.onrender.com
      - key: N8N_HOST
        value: 0.0.0.0
      - key: N8N_PORT
        value: 5678
      - key: N8N_ENCRYPTION_KEY
        generateValue: true
