services:
  - type: web
    name: n8n
    runtime: docker
    region: ohio
    plan: free
    branch: main
    dockerfilePath: ./Dockerfile
    envVars:
      - key: N8N_BASIC_AUTH_USER
        sync: false
      - key: N8N_BASIC_AUTH_PASSWORD
        sync: false
      - key: N8N_HOST
        value: 0.0.0.0
      - key: N8N_PORT
        value: 5678
      - key: N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS
        value: 'true'
